using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SharedModels
{
    public class ArticleCreatedEvent
    {
        public long Id { get; set; }              // Auto-generated by DB
        public string Title { get; set; } = null!;
        public string Content { get; set; } = null!;
        public string Author { get; set; } = null!;
        public DateTime PublishedAt { get; set; } = DateTime.UtcNow;
        public string Continent { get; set; } = null!;

        public string? TraceParent { get; set; }
        public string? TraceState { get; set; }
    }
}
