services:
  articles-africa-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-africa-aricles:/var/opt/mssql
  articles-asia-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-asia-articles:/var/opt/mssql
  articles-antarctica-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-antarctica-articles:/var/opt/mssql
  articles-europe-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-europe-articles:/var/opt/mssql
  articles-north-america-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-north-america-articles:/var/opt/mssql
  articles-south-america-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-south-america-articles:/var/opt/mssql
  articles-oceania-db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-oceania-articles:/var/opt/mssql
    articles-global-db:
      image: mcr.microsoft.com/azure-sql-edge:latest
      environment:
        MSSQL_SA_PASSWORD: "SuperSecret7!"
        ACCEPT_EULA: "Y"
      volumes:
        - mssql-global-articles:/var/opt/mssql
  articleservice:
    build:
      context: .
      dockerfile: ArticleService/dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - serviceName: articles-africa-db
      - serviceName: articles-asia-db
      - serviceName: articles-antarctica-db
      - serviceName: articles-europe-db
      - serviceName: articles-north-america-db
      - serviceName: articles-south-america-db
      - serviceName: articles-oceania-db
      - serviceName: articles-global-db
    replicas: 2
volumes:
  mssql-africa-aricles:
  mssql-asia-articles:
  mssql-antarctica-articles:
  mssql-europe-articles:
  mssql-north-america-articles:
  mssql-south-america-articles:
  mssql-oceania-articles:
  mssql-global-articles: