services:
  rabbitmq:
    user: "0"
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "5672:5672"
      - "15672:15672"
  
  publisherservice:
    build:
      context: .
      dockerfile: ./PublisherService/Dockerfile
    ports:
      - "8013:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      rabbitmq:
        condition: service_healthy

  articleservice:
    build:
      context: .
      dockerfile: ./ArticleService/dockerfile
    ports:
      - "8023:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    depends_on:
      rabbitmq:
        condition: service_healthy