services:
  draftservice:
    build:
      context: .
      dockerfile: DraftService/Dockerfile
    ports:
      - "6003:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - ConnectionStrings__DraftDatabase=Server=draft-db;Database=Drafts;User Id=sa;Password=SuperSecret7!;Encrypt=false;
    depends_on:
      - draft-db
  draft-db:
        image: mcr.microsoft.com/azure-sql-edge:latest
        environment:
          MSSQL_SA_PASSWORD: "SuperSecret7!"
          ACCEPT_EULA: "Y"
        volumes:
          - mssql-drafts:/var/opt/mssql
  seq:
    image: datalust/seq
    ports:
      - "5341:5341"
      - "5342:80"
    environment:
      SEQ_FIRSTRUN_ADMINPASSWORD: "password"
      ACCEPT_EULA: "Y"
    volumes:
      - rps_seq_data:/data

volumes:
    mssql-drafts:
    rps_seq_data:
      