public enum Continent
{
    africa,
    asia,
    antarctica,
    europe,
    north_america,
    south_america,
    oceania,
    global
}

public class Article
{
    public long Id { get; set; }              // Auto-generated by DB
    public string Title { get; set; } = null!;
    public string Content { get; set; } = null!;
    public string Author { get; set; } = null!;
    public DateTime PublishedAt { get; set; } = DateTime.UtcNow;
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public Continent Continent { get; set; } = Continent.Global;

}




