
    public class Comment
    {
        public long Id { get; set; }              // Auto-generated by DB
        public long ArticleId { get; set; }

        public string ArticleContinent { get; set; } = null!;
        public string TextContent { get; set; } = null!;
        public string Username { get; set; } = null!;
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    }
